global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8000"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: "xgboost-service"
    static_configs:
      - targets: ["xgboost-service:8001"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "pytorch-service"
    static_configs:
      - targets: ["pytorch-service:8002"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "fallback-service"
    static_configs:
      - targets: ["fallback-service:8003"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
